export default {
	shadowStore: [
		'shadowStore',
		{
			type: 'autogenerated',
			dirName: 'shadowStore',
		},
	],
	licenseSystem: [
		'licenseSystem',
		{
			type: 'autogenerated',
			dirName: 'licenseSystem',
		},
	],
	legacy: [
		{
			type: 'autogenerated',
			dirName: 'legacy',
		},
	],
	spark: [
		{
			type: 'autogenerated',
			dirName: 'spark',
		},
	],
};
