export default {
	shadowStore: [
		'shadowStore',
		{
			type: 'autogenerated',
			dirName: 'shadowStore',
		},
	],
	licenseSystem: [
		'licenseSystem',
		{
			type: 'autogenerated',
			dirName: 'licenseSystem',
		},
	],
	cdnManager: [
		'cdnManager',
		{
			type: 'autogenerated',
			dirName: 'cdnManager',
		},
	],
	shadowStatus: [
		'shadowStatus',
		{
			type: 'autogenerated',
			dirName: 'shadowStatus',
		},
	],
	communityTemplate: [
		'communityTemplate',
		{
			type: 'autogenerated',
			dirName: 'communityTemplate',
		},
	],
	personalLanding: [
		'personalLanding',
		{
			type: 'autogenerated',
			dirName: 'personalLanding',
		},
	],
	shopifyBot: [
		'shopifyBot',
		{
			type: 'autogenerated',
			dirName: 'shopifyBot',
		},
	],
	spark: [
		{
			type: 'autogenerated',
			dirName: 'spark',
		},
	],
	legacy: [
		{
			type: 'autogenerated',
			dirName: 'legacy',
		},
	],
};
